"""Reusable GEO download and processing package."""

from geo_processing import DatasetDetectionResult, detect_dataset

from .download import (
    DownloadConfig,
    DownloadModuleError,
    GeoDownloadError,
    RemoteCandidate,
    discover_external_sources,
    discover_platform_candidates,
    discover_sample_level_candidates,
    discover_series_level_candidates,
    discover_series_supplementary_candidates,
    download_core_geo_records,
    download_full_family_soft,
    execute_download_plan,
    load_existing_full_family_soft,
    parse_existing_full_family_soft,
    score_remote_candidate,
    score_remote_candidates,
    select_remote_download_plan,
    should_probe_sample_level,
)
from .process import (
    AnnotationError,
    CleaningError,
    MatrixBuildError,
    MetadataParseError,
    ProcessConfig,
    ProcessModuleError,
    process_from_gse_object,
    process_from_local_family_soft,
    run_processing_pipeline,
)

__all__ = [
    "AnnotationError",
    "CleaningError",
    "DatasetDetectionResult",
    "DownloadConfig",
    "DownloadModuleError",
    "GeoDownloadError",
    "MatrixBuildError",
    "MetadataParseError",
    "ProcessConfig",
    "ProcessModuleError",
    "RemoteCandidate",
    "discover_external_sources",
    "discover_platform_candidates",
    "discover_sample_level_candidates",
    "discover_series_level_candidates",
    "discover_series_supplementary_candidates",
    "download_core_geo_records",
    "download_full_family_soft",
    "detect_dataset",
    "execute_download_plan",
    "load_existing_full_family_soft",
    "parse_existing_full_family_soft",
    "process_from_gse_object",
    "process_from_local_family_soft",
    "run_processing_pipeline",
    "score_remote_candidate",
    "score_remote_candidates",
    "select_remote_download_plan",
    "should_probe_sample_level",
]
