from __future__ import annotations

from app.labtools.recipes.recipe_models import RECIPE_REVIEW_NOTICE, Recipe, RecipeComponent


COMMON_NOTES = (
    "按目标体积线性缩放后，请按实验室 SOP、试剂标签和仪器要求复核。",
    "pH、温度、灭菌、过滤和保存条件不在本地工具中自动决定。",
)


def built_in_recipes() -> tuple[Recipe, ...]:
    return (
        Recipe(
            recipe_id="pbs_1x_reference",
            name="PBS 1× 参考配方",
            category="基础缓冲液",
            description="常用磷酸盐缓冲液参考配方。",
            stock_concentration="1×",
            default_volume=1000,
            default_volume_unit="mL",
            components=(
                RecipeComponent("NaCl", 8.0, "g", "主要盐"),
                RecipeComponent("KCl", 0.2, "g", "辅助盐"),
                RecipeComponent("Na2HPO4", 1.44, "g", "缓冲组分"),
                RecipeComponent("KH2PO4", 0.24, "g", "缓冲组分"),
                RecipeComponent("纯化水补足至", 1000, "mL", "溶剂"),
            ),
            preparation_notes=COMMON_NOTES,
            safety_notes=("不替代实验室 SOP；使用前确认 pH、渗透压和无菌要求。",),
            source_label="BioMedPilot 内置科研参考配方",
            version="2026.05-local",
        ),
        Recipe(
            recipe_id="tbs_1x_reference",
            name="TBS 1× 参考配方",
            category="基础缓冲液",
            description="Tris-buffered saline 本地参考配方。",
            stock_concentration="1×",
            default_volume=1000,
            default_volume_unit="mL",
            components=(
                RecipeComponent("Tris base", 2.42, "g", "缓冲组分"),
                RecipeComponent("NaCl", 8.0, "g", "主要盐"),
                RecipeComponent("纯化水补足至", 1000, "mL", "溶剂"),
            ),
            preparation_notes=COMMON_NOTES + ("pH 调整请按实验室 SOP 执行，本工具不自动给出酸碱加入量。",),
            safety_notes=("配制前确认目标 pH、用途和保存条件。",),
            source_label="BioMedPilot 内置科研参考配方",
            version="2026.05-local",
        ),
        Recipe(
            recipe_id="tae_50x_reference",
            name="TAE 50× 参考配方",
            category="电泳缓冲液",
            description="琼脂糖电泳常用 TAE stock 参考配方。",
            stock_concentration="50×",
            default_volume=1000,
            default_volume_unit="mL",
            components=(
                RecipeComponent("Tris base", 242.0, "g", "缓冲组分"),
                RecipeComponent("EDTA", 18.6, "g", "螯合组分"),
                RecipeComponent("纯化水补足至", 1000, "mL", "溶剂"),
            ),
            preparation_notes=COMMON_NOTES + ("酸碱调节步骤请按实验室 SOP 执行。",),
            safety_notes=("处理粉末和调 pH 时使用合适个人防护；本工具不替代安全数据表。",),
            source_label="BioMedPilot 内置科研参考配方",
            version="2026.05-local",
        ),
        Recipe(
            recipe_id="tbe_10x_reference",
            name="TBE 10× 参考配方",
            category="电泳缓冲液",
            description="TBE stock 本地参考配方。",
            stock_concentration="10×",
            default_volume=1000,
            default_volume_unit="mL",
            components=(
                RecipeComponent("Tris base", 108.0, "g", "缓冲组分"),
                RecipeComponent("Boric acid", 55.0, "g", "缓冲组分"),
                RecipeComponent("EDTA", 7.44, "g", "螯合组分"),
                RecipeComponent("纯化水补足至", 1000, "mL", "溶剂"),
            ),
            preparation_notes=COMMON_NOTES,
            safety_notes=("处理粉末时使用合适个人防护；按安全数据表和 SOP 操作。",),
            source_label="BioMedPilot 内置科研参考配方",
            version="2026.05-local",
        ),
        Recipe(
            recipe_id="tris_hcl_1m_reference",
            name="Tris-HCl 1 M 参考配方",
            category="基础缓冲液",
            description="Tris-HCl 缓冲液配制参考；pH 调整需人工复核。",
            stock_concentration="1×",
            default_volume=1000,
            default_volume_unit="mL",
            components=(
                RecipeComponent("Tris base", 121.14, "g", "缓冲组分"),
                RecipeComponent("纯化水补足至", 1000, "mL", "溶剂"),
            ),
            preparation_notes=COMMON_NOTES + ("目标 pH 与酸加入量请按 SOP 和 pH 计读数人工确定。",),
            safety_notes=("酸碱调节涉及腐蚀性试剂时，必须按实验室安全规范操作。",),
            source_label="BioMedPilot 内置科研参考配方",
            version="2026.05-local",
        ),
        Recipe(
            recipe_id="sds_page_running_buffer_10x_reference",
            name="SDS-PAGE Running Buffer 10× 参考配方",
            category="蛋白实验缓冲液",
            description="SDS-PAGE 电泳缓冲液 stock 参考配方。",
            stock_concentration="10×",
            default_volume=1000,
            default_volume_unit="mL",
            components=(
                RecipeComponent("Tris base", 30.3, "g", "缓冲组分"),
                RecipeComponent("Glycine", 144.0, "g", "缓冲组分"),
                RecipeComponent("SDS", 10.0, "g", "表面活性剂"),
                RecipeComponent("纯化水补足至", 1000, "mL", "溶剂"),
            ),
            preparation_notes=COMMON_NOTES,
            safety_notes=("SDS 等试剂需按安全数据表处理；避免吸入粉末。",),
            source_label="BioMedPilot 内置科研参考配方",
            version="2026.05-local",
        ),
        Recipe(
            recipe_id="western_transfer_buffer_methanol_free_reference",
            name="Western Transfer Buffer 1× 参考配方（不含甲醇）",
            category="蛋白实验缓冲液",
            description="转膜缓冲液本地参考；未包含甲醇相关步骤。",
            stock_concentration="1×",
            default_volume=1000,
            default_volume_unit="mL",
            components=(
                RecipeComponent("Tris base", 3.03, "g", "缓冲组分"),
                RecipeComponent("Glycine", 14.4, "g", "缓冲组分"),
                RecipeComponent("纯化水补足至", 1000, "mL", "溶剂"),
            ),
            preparation_notes=COMMON_NOTES + ("如实验需要甲醇或其他添加剂，请按实验室 SOP 和试剂说明书处理。",),
            safety_notes=("本工具不提供挥发性或高风险添加剂的详细制备流程。",),
            source_label="BioMedPilot 内置科研参考配方",
            version="2026.05-local",
        ),
        Recipe(
            recipe_id="blocking_buffer_milk_tbst_reference",
            name="Blocking Buffer 示例",
            category="蛋白实验缓冲液",
            description="常见封闭液示例，需按抗体和实验体系复核。",
            stock_concentration="1×",
            default_volume=100,
            default_volume_unit="mL",
            components=(
                RecipeComponent("脱脂奶粉", 5.0, "g", "封闭剂"),
                RecipeComponent("TBST 或 TBS 补足至", 100.0, "mL", "溶剂"),
            ),
            preparation_notes=COMMON_NOTES + ("封闭剂比例和缓冲液类型应按抗体说明书确认。",),
            safety_notes=("避免把示例配方直接视为特定抗体的标准方案。",),
            source_label="BioMedPilot 内置科研参考配方",
            version="2026.05-local",
        ),
        Recipe(
            recipe_id="agarose_gel_1pct_reference",
            name="Agarose Gel 1% 参考计算",
            category="电泳配制",
            description="1% agarose gel 本地计算示例，不包含染料或成像试剂。",
            stock_concentration="1×",
            default_volume=100,
            default_volume_unit="mL",
            components=(
                RecipeComponent("Agarose", 1.0, "g", "凝胶基质"),
                RecipeComponent("TAE/TBE 工作液补足至", 100.0, "mL", "缓冲液"),
            ),
            preparation_notes=COMMON_NOTES + ("染料、加热和成像步骤请按实验室 SOP 执行。",),
            safety_notes=("加热溶液和凝胶处理有烫伤风险；本工具不提供染料处理流程。",),
            source_label="BioMedPilot 内置科研参考配方",
            version="2026.05-local",
        ),
        Recipe(
            recipe_id="ripa_scaffold_reference",
            name="RIPA Buffer 示例框架",
            category="裂解缓冲液",
            description="示例配方框架，需按实验室 SOP 和试剂说明复核。",
            stock_concentration="1×",
            default_volume=100,
            default_volume_unit="mL",
            components=(
                RecipeComponent("基础缓冲液", 100.0, "mL", "溶剂"),
            ),
            preparation_notes=(
                "本条仅作为记录框架，不提供高风险或特定抑制剂的详细制备流程。",
                "请使用实验室已批准 SOP 和试剂说明书确认组分、浓度、添加顺序和保存条件。",
            ),
            safety_notes=("裂解液和添加剂可能具有刺激性或毒性；必须按安全数据表和 SOP 操作。",),
            source_label="BioMedPilot 内置科研参考配方",
            version="2026.05-local",
            review_notice=RECIPE_REVIEW_NOTICE,
        ),
    )
