"""Public LabTools package extracted from BioMedPilot."""

from labtools.calculators import (
    CALCULATION_REVIEW_NOTICE,
    CalculationError,
    CalculationRecord,
    CalculationResult,
    CellSeedingInput,
    CellSeedingResult,
    DilutionInput,
    DilutionResult,
    FORMULA_RESULT_SECTIONS,
    FORMULA_SPECS,
    FormulaExampleSpec,
    FormulaFieldSpec,
    FormulaSolveTargetSpec,
    FormulaSpec,
    MassMolarityInput,
    MassMolarityResult,
    LOW_MASS_WARNING,
    LOW_VOLUME_WARNING,
    QUICK_CALCULATOR_TASKS,
    QpcrMixInput,
    QpcrMixResult,
    QUICK_CALCULATOR_FIELD_TYPES,
    QUICK_TASK_RESULT_SECTIONS,
    QuickCalculatorTaskSpec,
    TINY_VALUE_WARNING,
    WesternBlotLoadingInput,
    WesternBlotLoadingResult,
    calculate_serial_dilution,
    calculate_cell_seeding,
    calculate_cell_seeding_v1,
    calculate_dilution,
    calculate_dilution_v1,
    calculate_mass_for_molar_solution,
    calculate_mass_molarity_v1,
    calculate_molar_concentration,
    calculate_qpcr_mix,
    calculate_qpcr_mix_v1,
    calculate_solution_preparation,
    calculate_western_blot_loading_v1,
    convert_concentration,
    convert_mass_concentration_unit,
    format_cell_seeding_copy_text,
    format_dilution_copy_text,
    format_mass_molarity_copy_text,
    get_formula_spec,
    get_quick_calculator_task,
    list_formula_specs,
    list_quick_calculator_tasks,
    solve_concentration_bridge,
    solve_dilution_equation,
    solve_percent_solution,
    solve_solution_preparation_formula,
    solve_stock_working_solution,
    supported_units_for_formula_field,
    supported_amount_units,
    supported_concentration_units,
    supported_mass_units,
    supported_molecular_weight_units,
    supported_quick_calculator_units,
    supported_volume_units,
)
from labtools.shared.version import APP_VERSION as __version__


def smoke_test() -> dict[str, object]:
    """Import key public surfaces and return a small status payload."""

    from labtools import cell_culture, elisa, lan_server, local_data, pcr_qpcr, reagent_templates, western_blot

    return {
        "version": __version__,
        "modules": (
            "labtools.calculators",
            reagent_templates.__name__,
            local_data.__name__,
            lan_server.__name__,
            western_blot.__name__,
            pcr_qpcr.__name__,
            cell_culture.__name__,
            elisa.__name__,
        ),
    }


__all__ = [
    "__version__",
    "CALCULATION_REVIEW_NOTICE",
    "CalculationError",
    "CalculationRecord",
    "CalculationResult",
    "CellSeedingInput",
    "CellSeedingResult",
    "DilutionInput",
    "DilutionResult",
    "FORMULA_RESULT_SECTIONS",
    "FORMULA_SPECS",
    "FormulaExampleSpec",
    "FormulaFieldSpec",
    "FormulaSolveTargetSpec",
    "FormulaSpec",
    "MassMolarityInput",
    "MassMolarityResult",
    "LOW_MASS_WARNING",
    "LOW_VOLUME_WARNING",
    "QUICK_CALCULATOR_TASKS",
    "QpcrMixInput",
    "QpcrMixResult",
    "QUICK_CALCULATOR_FIELD_TYPES",
    "QUICK_TASK_RESULT_SECTIONS",
    "QuickCalculatorTaskSpec",
    "TINY_VALUE_WARNING",
    "WesternBlotLoadingInput",
    "WesternBlotLoadingResult",
    "calculate_cell_seeding",
    "calculate_cell_seeding_v1",
    "calculate_dilution",
    "calculate_dilution_v1",
    "calculate_mass_for_molar_solution",
    "calculate_mass_molarity_v1",
    "calculate_molar_concentration",
    "calculate_qpcr_mix",
    "calculate_qpcr_mix_v1",
    "calculate_solution_preparation",
    "calculate_serial_dilution",
    "calculate_western_blot_loading_v1",
    "convert_concentration",
    "convert_mass_concentration_unit",
    "format_cell_seeding_copy_text",
    "format_dilution_copy_text",
    "format_mass_molarity_copy_text",
    "get_formula_spec",
    "get_quick_calculator_task",
    "list_formula_specs",
    "list_quick_calculator_tasks",
    "solve_concentration_bridge",
    "solve_dilution_equation",
    "solve_percent_solution",
    "solve_solution_preparation_formula",
    "solve_stock_working_solution",
    "supported_units_for_formula_field",
    "supported_amount_units",
    "supported_concentration_units",
    "supported_mass_units",
    "supported_molecular_weight_units",
    "supported_quick_calculator_units",
    "supported_volume_units",
    "smoke_test",
]
