import json

ZH_ALIASES = {
    # ===== 疾病：甲状腺 =====
    "甲状腺肿瘤": "甲状腺肿瘤",
    "甲状腺肿物": "甲状腺肿瘤",
    "甲状腺肿瘤性病变": "甲状腺肿瘤",

    "甲状腺癌": "甲状腺癌",
    "甲癌": "甲状腺癌",
    "甲状腺恶性肿瘤": "甲状腺癌",

    "甲状腺乳头状癌": "甲状腺乳头状癌",
    "甲状腺乳头癌": "甲状腺乳头状癌",
    "乳头状甲状腺癌": "甲状腺乳头状癌",
    "乳头癌": "甲状腺乳头状癌",
    "甲乳癌": "甲状腺乳头状癌",
    "PTC": "甲状腺乳头状癌",

    "甲状腺滤泡癌": "甲状腺滤泡癌",
    "滤泡状甲状腺癌": "甲状腺滤泡癌",
    "FTC": "甲状腺滤泡癌",

    "甲状腺髓样癌": "甲状腺髓样癌",
    "髓样甲状腺癌": "甲状腺髓样癌",
    "髓样癌": "甲状腺髓样癌",
    "MTC": "甲状腺髓样癌",

    "甲状腺未分化癌": "甲状腺未分化癌",
    "未分化甲状腺癌": "甲状腺未分化癌",
    "未分化甲癌": "甲状腺未分化癌",
    "ATC": "甲状腺未分化癌",

    "甲状腺低分化癌": "甲状腺低分化癌",
    "低分化甲状腺癌": "甲状腺低分化癌",
    "PDTC": "甲状腺低分化癌",

    "甲状腺嗜酸细胞癌": "甲状腺嗜酸细胞癌",
    "Hurthle细胞癌": "甲状腺嗜酸细胞癌",
    "Hürthle细胞癌": "甲状腺嗜酸细胞癌",

    "甲状腺腺瘤": "甲状腺腺瘤",
    "滤泡性甲状腺腺瘤": "甲状腺腺瘤",
    "甲状腺结节": "甲状腺结节",

    # ===== 疾病：甲状旁腺 =====
    "甲状旁腺肿瘤": "甲状旁腺肿瘤",
    "甲旁腺肿瘤": "甲状旁腺肿瘤",
    "甲状旁腺腺瘤": "甲状旁腺腺瘤",
    "甲旁腺瘤": "甲状旁腺腺瘤",
    "甲旁腺腺瘤": "甲状旁腺腺瘤",
    "甲状旁腺癌": "甲状旁腺癌",
    "甲旁癌": "甲状旁腺癌",
    "甲旁腺癌": "甲状旁腺癌",
    "甲状旁腺增生": "甲状旁腺增生",

    # ===== 疾病：垂体 =====
    "垂体肿瘤": "垂体肿瘤",
    "垂体腺瘤": "垂体腺瘤",
    "垂体瘤": "垂体腺瘤",
    "垂体神经内分泌肿瘤": "垂体神经内分泌肿瘤",
    "垂体神经内分泌瘤": "垂体神经内分泌肿瘤",
    "PitNET": "垂体神经内分泌肿瘤",
    "垂体癌": "垂体癌",
    "泌乳素瘤": "泌乳素瘤",
    "催乳素瘤": "泌乳素瘤",
    "PRL瘤": "泌乳素瘤",
    "生长激素腺瘤": "生长激素腺瘤",
    "GH瘤": "生长激素腺瘤",
    "促肾上腺皮质激素腺瘤": "促肾上腺皮质激素腺瘤",
    "ACTH瘤": "促肾上腺皮质激素腺瘤",
    "无功能垂体腺瘤": "无功能垂体腺瘤",
    "NFPA": "无功能垂体腺瘤",

    # ===== 疾病：肾上腺 =====
    "肾上腺肿瘤": "肾上腺肿瘤",
    "肾上腺皮质肿瘤": "肾上腺肿瘤",
    "肾上腺皮质腺瘤": "肾上腺皮质腺瘤",
    "肾上腺腺瘤": "肾上腺皮质腺瘤",
    "肾上腺皮质癌": "肾上腺皮质癌",
    "肾上腺癌": "肾上腺皮质癌",
    "ACC": "肾上腺皮质癌",
    "皮质醇分泌性肾上腺瘤": "皮质醇分泌性肾上腺瘤",
    "库欣腺瘤": "皮质醇分泌性肾上腺瘤",
    "醛固酮瘤": "醛固酮瘤",
    "醛固酮分泌性腺瘤": "醛固酮瘤",
    "APA": "醛固酮瘤",

    # ===== 疾病：PCC/PGL =====
    "嗜铬细胞瘤": "嗜铬细胞瘤",
    "嗜铬瘤": "嗜铬细胞瘤",
    "PCC": "嗜铬细胞瘤",
    "副神经节瘤": "副神经节瘤",
    "PGL": "副神经节瘤",
    "头颈副神经节瘤": "头颈副神经节瘤",
    "家族性嗜铬细胞瘤副神经节瘤": "家族性嗜铬细胞瘤副神经节瘤",
    "家族性PCC/PGL": "家族性嗜铬细胞瘤副神经节瘤",

    # ===== 疾病：胰腺NET =====
    "胰腺神经内分泌肿瘤": "胰腺神经内分泌肿瘤",
    "胰腺神经内分泌瘤": "胰腺神经内分泌肿瘤",
    "胰腺内分泌肿瘤": "胰腺神经内分泌肿瘤",
    "胰岛细胞瘤": "胰腺神经内分泌肿瘤",
    "PanNET": "胰腺神经内分泌肿瘤",
    "pNET": "胰腺神经内分泌肿瘤",
    "胰岛素瘤": "胰岛素瘤",
    "胃泌素瘤": "胃泌素瘤",
    "胰高血糖素瘤": "胰高血糖素瘤",
    "生长抑素瘤": "生长抑素瘤",
    "VIP瘤": "VIP瘤",
    "非功能性胰腺神经内分泌肿瘤": "非功能性胰腺神经内分泌肿瘤",

    # ===== 疾病：其他NET =====
    "神经内分泌肿瘤": "神经内分泌肿瘤",
    "神经内分泌瘤": "神经内分泌肿瘤",
    "神经内分泌肿物": "神经内分泌肿瘤",
    "NET": "神经内分泌肿瘤",
    "NEN": "神经内分泌肿瘤",
    "神经内分泌癌": "神经内分泌癌",
    "NEC": "神经内分泌癌",
    "胃肠胰神经内分泌肿瘤": "胃肠胰神经内分泌肿瘤",
    "GEP-NET": "胃肠胰神经内分泌肿瘤",
    "肺神经内分泌肿瘤": "肺神经内分泌肿瘤",
    "肺类癌": "肺神经内分泌肿瘤",
    "胸腺神经内分泌肿瘤": "胸腺神经内分泌肿瘤",

    # ===== 综合征 =====
    "多发性内分泌腺瘤1型": "多发性内分泌腺瘤1型",
    "MEN1": "多发性内分泌腺瘤1型",
    "多发性内分泌腺瘤2型": "多发性内分泌腺瘤2型",
    "MEN2": "多发性内分泌腺瘤2型",
    "多发性内分泌腺瘤2A型": "多发性内分泌腺瘤2A型",
    "MEN2A": "多发性内分泌腺瘤2A型",
    "多发性内分泌腺瘤2B型": "多发性内分泌腺瘤2B型",
    "MEN2B": "多发性内分泌腺瘤2B型",
    "多发性内分泌腺瘤4型": "多发性内分泌腺瘤4型",
    "MEN4": "多发性内分泌腺瘤4型",
    "家族性非髓样甲状腺癌": "家族性非髓样甲状腺癌",
    "FNMTC": "家族性非髓样甲状腺癌",
    "家族性嗜铬细胞瘤副神经节瘤综合征": "家族性嗜铬细胞瘤副神经节瘤综合征",

    # ===== 常见测试入口 =====
    "乳腺癌": "乳腺癌",
    "乳癌": "乳腺癌",
    "乳腺恶性肿瘤": "乳腺癌",
    "三阴性乳腺癌": "三阴性乳腺癌",
    "TNBC": "三阴性乳腺癌",

    # ===== 暴露因素 =====
    "肥胖": "肥胖",
    "超重": "超重",
    "吸烟": "吸烟",
    "抽烟": "吸烟",
    "二手烟": "二手烟",
    "酒精": "酒精",
    "饮酒": "酒精",
    "喝酒": "酒精",
    "体力活动不足": "体力活动不足",
    "久坐": "久坐",
    "睡眠不足": "睡眠不足",
    "夜班": "夜班",
    "压力": "压力",
    "高脂饮食": "高脂饮食",
    "高糖饮食": "高糖饮食",
    "高盐饮食": "高盐饮食",
    "低碘": "低碘",
    "高碘": "高碘",
    "胆固醇摄入": "胆固醇摄入",
    "超加工食品": "超加工食品",
    "红肉": "红肉",
    "乳制品": "乳制品",
    "果糖": "果糖",
    "BMI升高": "BMI升高",
    "中心性肥胖": "中心性肥胖",
    "胰岛素抵抗": "胰岛素抵抗",
    "代谢综合征": "代谢综合征",
    "糖尿病": "糖尿病",
    "前驱糖尿病": "前驱糖尿病",
    "高胆固醇": "高胆固醇",
    "胆固醇": "高胆固醇",
    "高脂血症": "高脂血症",
    "辐射": "辐射",
    "电离辐射": "电离辐射",
    "职业暴露": "职业暴露",
    "空气污染": "空气污染",
    "农药": "农药",
    "重金属": "重金属",
    "内分泌干扰物": "内分泌干扰物",
    "双酚A": "双酚A",
    "邻苯二甲酸酯": "邻苯二甲酸酯",
    "激素替代治疗": "激素替代治疗",
    "口服避孕药": "口服避孕药",
    "糖皮质激素": "糖皮质激素",
    "放疗": "放疗",
    "化疗": "化疗",
    "靶向治疗": "靶向治疗",
    "二甲双胍": "二甲双胍",
    "他汀": "他汀",
    "雌激素暴露": "雌激素暴露",
    "雄激素暴露": "雄激素暴露",
    "孕激素暴露": "孕激素暴露",
    "妊娠": "妊娠",
    "绝经": "绝经",
    "青春期": "青春期",
    "高皮质醇": "高皮质醇",
    "高胰岛素": "高胰岛素",
    "慢性炎症": "慢性炎症",
    "自身免疫": "自身免疫",
    "病毒感染": "病毒感染",
    "HBV": "HBV",
    "HCV": "HCV",
    "幽门螺杆菌": "幽门螺杆菌",
    "家族史": "家族史",
    "遗传易感": "遗传易感",
    "RET胚系突变": "RET胚系突变",
    "SDHx突变": "SDHx突变",

    # ===== 人群 =====
    "儿童": "儿童",
    "小儿": "儿童",
    "青少年": "青少年",
    "少年": "青少年",
    "成人": "成人",
    "老年": "老年",
    "高龄": "老年",
    "女性": "女性",
    "女": "女性",
    "男性": "男性",
    "男": "男性",

    # ===== 国家 / 地区 =====
    "中国": "中国",
    "中国人": "中国",
    "美国": "美国",
    "美国人": "美国",
    "日本": "日本",
    "日本人": "日本",
    "韩国": "韩国",
    "韩国人": "韩国",
    "亚洲": "亚洲",
    "欧洲": "欧洲",
}
CANONICAL_DISEASE_TO_ENGLISH = {
    "甲状腺肿瘤": ["thyroid neoplasms", "thyroid neoplasm", "thyroid tumor", "thyroid cancer"],
    "甲状腺癌": ["thyroid cancer", "thyroid carcinoma", "thyroid neoplasm"],
    "甲状腺乳头状癌": ["papillary thyroid carcinoma", "papillary thyroid cancer", "PTC"],
    "甲状腺滤泡癌": ["follicular thyroid carcinoma", "FTC"],
    "甲状腺髓样癌": ["medullary thyroid carcinoma", "MTC"],
    "甲状腺未分化癌": ["anaplastic thyroid carcinoma", "ATC"],
    "甲状腺低分化癌": ["poorly differentiated thyroid carcinoma", "PDTC"],
    "甲状腺嗜酸细胞癌": ["hurthle cell carcinoma", "oncocytic thyroid carcinoma"],
    "甲状腺腺瘤": ["thyroid adenoma", "follicular adenoma of thyroid"],
    "甲状腺结节": ["thyroid nodule", "thyroid nodules"],

    "甲状旁腺肿瘤": ["parathyroid neoplasms", "parathyroid tumor"],
    "甲状旁腺腺瘤": ["parathyroid adenoma"],
    "甲状旁腺癌": ["parathyroid carcinoma", "parathyroid cancer"],
    "甲状旁腺增生": ["parathyroid hyperplasia"],

    "垂体肿瘤": ["pituitary neoplasms", "pituitary tumor"],
    "垂体腺瘤": ["pituitary adenoma"],
    "垂体神经内分泌肿瘤": ["pituitary neuroendocrine tumor", "PitNET"],
    "垂体癌": ["pituitary carcinoma"],
    "泌乳素瘤": ["prolactinoma", "lactotroph adenoma"],
    "生长激素腺瘤": ["somatotroph adenoma", "growth hormone secreting pituitary adenoma"],
    "促肾上腺皮质激素腺瘤": ["corticotroph adenoma", "ACTH-secreting pituitary adenoma"],
    "无功能垂体腺瘤": ["nonfunctioning pituitary adenoma", "NFPA"],

    "肾上腺肿瘤": ["adrenal gland neoplasms", "adrenal tumor"],
    "肾上腺皮质腺瘤": ["adrenocortical adenoma", "adrenal cortical adenoma"],
    "肾上腺皮质癌": ["adrenocortical carcinoma", "ACC"],
    "皮质醇分泌性肾上腺瘤": ["cortisol-producing adrenal adenoma"],
    "醛固酮瘤": ["aldosterone-producing adenoma", "APA"],

    "嗜铬细胞瘤": ["pheochromocytoma", "PCC"],
    "副神经节瘤": ["paraganglioma", "PGL"],
    "头颈副神经节瘤": ["head and neck paraganglioma"],
    "家族性嗜铬细胞瘤副神经节瘤": ["familial pheochromocytoma paraganglioma syndrome"],

    "胰腺神经内分泌肿瘤": ["pancreatic neuroendocrine tumor", "pancreatic neuroendocrine neoplasm", "pNET", "PanNET"],
    "胰岛素瘤": ["insulinoma"],
    "胃泌素瘤": ["gastrinoma"],
    "胰高血糖素瘤": ["glucagonoma"],
    "生长抑素瘤": ["somatostatinoma"],
    "VIP瘤": ["VIPoma", "vasoactive intestinal peptide tumor"],
    "非功能性胰腺神经内分泌肿瘤": ["nonfunctioning pancreatic neuroendocrine tumor"],

    "神经内分泌肿瘤": ["neuroendocrine tumor", "NET", "neuroendocrine neoplasm", "NEN"],
    "神经内分泌癌": ["neuroendocrine carcinoma", "NEC"],
    "胃肠胰神经内分泌肿瘤": ["gastroenteropancreatic neuroendocrine tumor", "GEP-NET"],
    "肺神经内分泌肿瘤": ["pulmonary neuroendocrine tumor", "lung neuroendocrine tumor"],
    "胸腺神经内分泌肿瘤": ["thymic neuroendocrine tumor"],

    "多发性内分泌腺瘤1型": ["multiple endocrine neoplasia type 1", "MEN1"],
    "多发性内分泌腺瘤2型": ["multiple endocrine neoplasia type 2", "MEN2"],
    "多发性内分泌腺瘤2A型": ["multiple endocrine neoplasia type 2A", "MEN2A"],
    "多发性内分泌腺瘤2B型": ["multiple endocrine neoplasia type 2B", "MEN2B"],
    "多发性内分泌腺瘤4型": ["multiple endocrine neoplasia type 4", "MEN4"],
    "家族性非髓样甲状腺癌": ["familial nonmedullary thyroid cancer", "FNMTC"],
    "家族性嗜铬细胞瘤副神经节瘤综合征": ["familial pheochromocytoma and paraganglioma syndrome"],

    "乳腺癌": ["breast neoplasms", "breast cancer", "breast carcinoma"],
    "三阴性乳腺癌": ["triple negative breast cancer", "TNBC"],

    # 暴露因素
    "肥胖": ["obesity", "obese"],
    "超重": ["overweight"],
    "吸烟": ["smoking", "smoker", "tobacco", "cigarette"],
    "二手烟": ["secondhand smoke", "passive smoking", "environmental tobacco smoke"],
    "酒精": ["alcohol", "ethanol", "alcohol consumption", "alcohol drinking", "alcohol intake"],
    "体力活动不足": ["physical inactivity", "sedentary lifestyle", "low physical activity"],
    "久坐": ["sedentary behavior", "sitting time"],
    "睡眠不足": ["sleep deprivation", "short sleep duration"],
    "夜班": ["night shift", "shift work"],
    "压力": ["stress", "psychological stress"],
    "高脂饮食": ["high-fat diet", "fat-rich diet"],
    "高糖饮食": ["high sugar diet", "high-sucrose diet"],
    "高盐饮食": ["high salt diet", "high sodium diet"],
    "低碘": ["iodine deficiency", "low iodine"],
    "高碘": ["excess iodine", "high iodine"],
    "胆固醇摄入": ["dietary cholesterol", "cholesterol intake"],
    "超加工食品": ["ultra-processed food", "ultra-processed foods", "UPF"],
    "红肉": ["red meat"],
    "乳制品": ["dairy products", "milk intake"],
    "果糖": ["fructose intake", "high fructose"],
    "BMI升高": ["body mass index", "BMI"],
    "中心性肥胖": ["central obesity", "abdominal obesity", "visceral obesity"],
    "胰岛素抵抗": ["insulin resistance"],
    "代谢综合征": ["metabolic syndrome"],
    "糖尿病": ["diabetes", "diabetes mellitus"],
    "前驱糖尿病": ["prediabetes", "pre-diabetes"],
    "高胆固醇": ["hypercholesterolemia", "high cholesterol", "cholesterol"],
    "高脂血症": ["hyperlipidemia", "dyslipidemia"],
    "辐射": ["radiation exposure", "irradiation"],
    "电离辐射": ["ionizing radiation"],
    "职业暴露": ["occupational exposure", "workplace exposure"],
    "空气污染": ["air pollution", "particulate matter", "PM2.5"],
    "农药": ["pesticide exposure", "pesticides"],
    "重金属": ["heavy metals", "cadmium", "lead", "arsenic", "mercury"],
    "内分泌干扰物": ["endocrine disruptor", "endocrine disrupting chemicals", "EDCs"],
    "双酚A": ["bisphenol A", "BPA"],
    "邻苯二甲酸酯": ["phthalates", "phthalate exposure"],
    "激素替代治疗": ["hormone replacement therapy", "HRT"],
    "口服避孕药": ["oral contraceptives", "birth control pills"],
    "糖皮质激素": ["glucocorticoids", "corticosteroids"],
    "放疗": ["radiotherapy", "radiation therapy"],
    "化疗": ["chemotherapy"],
    "靶向治疗": ["targeted therapy"],
    "二甲双胍": ["metformin"],
    "他汀": ["statin", "statins"],
    "雌激素暴露": ["estrogen exposure", "oestrogen exposure"],
    "雄激素暴露": ["androgen exposure"],
    "孕激素暴露": ["progesterone exposure", "progestin exposure"],
    "妊娠": ["pregnancy", "pregnant women"],
    "绝经": ["menopause", "postmenopausal"],
    "青春期": ["puberty", "pubertal"],
    "高皮质醇": ["hypercortisolism", "cortisol excess"],
    "高胰岛素": ["hyperinsulinemia", "insulin excess"],
    "慢性炎症": ["chronic inflammation"],
    "自身免疫": ["autoimmune", "autoimmunity"],
    "病毒感染": ["viral infection"],
    "HBV": ["hepatitis B virus", "HBV"],
    "HCV": ["hepatitis C virus", "HCV"],
    "幽门螺杆菌": ["Helicobacter pylori", "H. pylori"],
    "家族史": ["family history", "familial"],
    "遗传易感": ["genetic susceptibility", "hereditary"],
    "RET胚系突变": ["RET germline mutation"],
    "SDHx突变": ["SDHB", "SDHD", "SDHC", "SDHA"],

    # 人群
    "儿童": ["child", "children", "pediatric", "paediatric"],
    "青少年": ["adolescent", "adolescents", "youth"],
    "成人": ["adult", "adults"],
    "老年": ["aged", "elderly", "older adults"],
    "女性": ["female", "females", "woman", "women"],
    "男性": ["male", "males", "man", "men"],

    # 国家地区
    "中国": ["china", "chinese"],
    "美国": ["united states", "USA", "US", "american"],
    "日本": ["japan", "japanese"],
    "韩国": ["south korea", "korea", "korean"],
    "亚洲": ["asia", "asian"],
    "欧洲": ["europe", "european"],
}
def normalize_terms(text: str, alias_map: dict) -> list[str]:
    matched = []
    # 长词优先，避免“甲乳癌”误命中“乳癌”
    for zh_alias, canonical in sorted(alias_map.items(), key=lambda x: len(x[0]), reverse=True):
        if zh_alias in text:
            matched.append(canonical)
            text = text.replace(zh_alias, " " * len(zh_alias))
    return list(dict.fromkeys(matched))
def expand_terms(canonical_terms: list[str], mapping: dict) -> list[str]:
    terms = []
    for c in canonical_terms:
        terms.extend(mapping.get(c, [c]))
    return list(dict.fromkeys(terms))


def build_query_from_terms(terms: list[str]) -> str:
    if not terms:
        return ""
    return " OR ".join(f'"{t}"' for t in terms)
def build_structured_query(chinese_text: str) -> str:
    canonical_terms = normalize_terms(chinese_text, ZH_DISEASE_ALIASES)
    english_terms = expand_terms(canonical_terms, CANONICAL_DISEASE_TO_ENGLISH)
    return build_query_from_terms(english_terms)
