"""Disease term dictionary for Chinese-driven GEO search."""

from __future__ import annotations


def _entry(canonical: str, aliases: list[str], english_terms: list[str]) -> dict:
    return {
        "canonical": canonical,
        "aliases": aliases,
        "english_terms": english_terms,
    }


DISEASE_TERMS = [
    _entry("癌症", ["癌症", "恶性肿瘤", "肿瘤"], ["cancer", "carcinoma", "tumor", "neoplasm"]),
    _entry("甲状腺癌", ["甲状腺癌", "thyroid cancer"], ["thyroid cancer", "thyroid carcinoma"]),
    _entry("甲状腺乳头状癌", ["甲状腺乳头状癌", "乳头状甲状腺癌", "甲乳癌", "ptc"], ["papillary thyroid carcinoma", "PTC"]),
    _entry("滤泡状甲状腺癌", ["滤泡状甲状腺癌", "甲状腺滤泡癌", "滤泡型甲状腺癌", "ftc"], ["follicular thyroid carcinoma", "FTC"]),
    _entry("未分化甲状腺癌", ["未分化甲状腺癌", "甲状腺未分化癌", "间变性甲状腺癌", "甲状腺间变癌", "atc"], ["anaplastic thyroid carcinoma", "ATC"]),
    _entry("低分化甲状腺癌", ["低分化甲状腺癌", "甲状腺低分化癌", "低分化甲癌", "pdtc"], ["poorly differentiated thyroid carcinoma", "PDTC"]),
    _entry("甲状腺髓样癌", ["甲状腺髓样癌", "髓样甲状腺癌", "mtc"], ["medullary thyroid carcinoma", "MTC"]),
    _entry(
        "甲状腺嗜酸细胞性肿瘤",
        ["甲状腺嗜酸细胞性肿瘤", "嗜酸细胞性甲状腺肿瘤", "hurthle", "hürthle", "甲状腺hurthle细胞肿瘤"],
        ["oncocytic thyroid tumor", "Hürthle cell thyroid tumor", "Hurthle cell thyroid tumor", "oncocytic thyroid neoplasm"],
    ),
    _entry("甲状腺腺瘤", ["甲状腺腺瘤", "滤泡性腺瘤"], ["thyroid adenoma", "follicular adenoma"]),
    _entry("甲状腺结节", ["甲状腺结节"], ["thyroid nodule", "thyroid nodules"]),
    _entry("甲状腺炎", ["桥本甲状腺炎", "甲状腺炎", "自身免疫性甲状腺炎"], ["thyroiditis", "Hashimoto thyroiditis", "autoimmune thyroiditis"]),
    _entry("乳腺癌", ["乳腺癌", "乳癌", "breast cancer"], ["breast cancer", "breast carcinoma"]),
    _entry("三阴性乳腺癌", ["三阴性乳腺癌", "tnbc"], ["triple negative breast cancer", "TNBC"]),
    _entry("her2阳性乳腺癌", ["her2阳性乳腺癌", "her2+乳腺癌"], ["HER2 positive breast cancer", "HER2+ breast cancer"]),
    _entry("肺癌", ["肺癌", "lung cancer"], ["lung cancer", "lung carcinoma"]),
    _entry("非小细胞肺癌", ["非小细胞肺癌", "nsclc"], ["non small cell lung cancer", "NSCLC"]),
    _entry("肺腺癌", ["肺腺癌", "luad"], ["lung adenocarcinoma", "LUAD"]),
    _entry("肺鳞癌", ["肺鳞癌", "lusc"], ["lung squamous cell carcinoma", "LUSC"]),
    _entry("小细胞肺癌", ["小细胞肺癌", "sclc"], ["small cell lung cancer", "SCLC"]),
    _entry("肝癌", ["肝癌", "原发性肝癌", "肝细胞癌", "hcc"], ["hepatocellular carcinoma", "HCC", "liver cancer"]),
    _entry("胆管癌", ["胆管癌", "胆管细胞癌", "cca"], ["cholangiocarcinoma", "CCA", "bile duct cancer"]),
    _entry("结直肠癌", ["结直肠癌", "肠癌", "crc"], ["colorectal cancer", "CRC", "colorectal carcinoma"]),
    _entry("结肠癌", ["结肠癌", "colon cancer"], ["colon cancer", "colon carcinoma"]),
    _entry("直肠癌", ["直肠癌", "rectal cancer"], ["rectal cancer", "rectal carcinoma"]),
    _entry("胃癌", ["胃癌"], ["gastric cancer", "stomach cancer", "gastric carcinoma"]),
    _entry("食管癌", ["食管癌", "食道癌"], ["esophageal cancer", "esophageal carcinoma"]),
    _entry("食管鳞癌", ["食管鳞癌", "escc"], ["esophageal squamous cell carcinoma", "ESCC"]),
    _entry("胰腺癌", ["胰腺癌", "胰癌"], ["pancreatic cancer", "pancreatic carcinoma"]),
    _entry("胰腺导管腺癌", ["胰腺导管腺癌", "pdac"], ["pancreatic ductal adenocarcinoma", "PDAC"]),
    _entry("胆囊癌", ["胆囊癌"], ["gallbladder cancer", "gallbladder carcinoma"]),
    _entry("乳头状肾细胞癌", ["乳头状肾细胞癌", "prcc"], ["papillary renal cell carcinoma", "PRCC"]),
    _entry("透明细胞肾细胞癌", ["透明细胞肾细胞癌", "ccrcc"], ["clear cell renal cell carcinoma", "ccRCC"]),
    _entry("肾嫌色细胞癌", ["肾嫌色细胞癌", "chrcc"], ["chromophobe renal cell carcinoma", "chRCC"]),
    _entry("肾癌", ["肾癌", "肾细胞癌", "rcc"], ["renal cell carcinoma", "RCC", "kidney cancer"]),
    _entry("膀胱癌", ["膀胱癌"], ["bladder cancer", "bladder carcinoma"]),
    _entry("前列腺癌", ["前列腺癌"], ["prostate cancer", "prostate carcinoma"]),
    _entry("卵巢癌", ["卵巢癌"], ["ovarian cancer", "ovarian carcinoma"]),
    _entry("高级别浆液性卵巢癌", ["高级别浆液性卵巢癌", "hgsc", "高等级浆液性卵巢癌"], ["high grade serous ovarian carcinoma", "HGSC"]),
    _entry("子宫内膜癌", ["子宫内膜癌"], ["endometrial cancer", "endometrial carcinoma"]),
    _entry("宫颈癌", ["宫颈癌"], ["cervical cancer", "cervical carcinoma"]),
    _entry("子宫肉瘤", ["子宫肉瘤"], ["uterine sarcoma"]),
    _entry("黑色素瘤", ["黑色素瘤", "melanoma"], ["melanoma"]),
    _entry("胶质瘤", ["胶质瘤", "glioma"], ["glioma"]),
    _entry("胶质母细胞瘤", ["胶质母细胞瘤", "gbm"], ["glioblastoma", "GBM"]),
    _entry("神经母细胞瘤", ["神经母细胞瘤"], ["neuroblastoma"]),
    _entry("骨肉瘤", ["骨肉瘤"], ["osteosarcoma"]),
    _entry("尤文肉瘤", ["尤文肉瘤", "ewing肉瘤"], ["Ewing sarcoma"]),
    _entry("软组织肉瘤", ["软组织肉瘤"], ["soft tissue sarcoma"]),
    _entry("横纹肌肉瘤", ["横纹肌肉瘤"], ["rhabdomyosarcoma"]),
    _entry("头颈癌", ["头颈癌"], ["head and neck cancer", "head and neck carcinoma"]),
    _entry("头颈鳞癌", ["头颈鳞癌", "hnscc"], ["head and neck squamous cell carcinoma", "HNSCC"]),
    _entry("口腔鳞癌", ["口腔鳞癌", "口腔癌"], ["oral squamous cell carcinoma", "OSCC"]),
    _entry("鼻咽癌", ["鼻咽癌", "npc"], ["nasopharyngeal carcinoma", "NPC"]),
    _entry("喉癌", ["喉癌"], ["laryngeal cancer", "laryngeal carcinoma"]),
    _entry("间皮瘤", ["间皮瘤", "胸膜间皮瘤"], ["mesothelioma", "pleural mesothelioma"]),
    _entry("白血病", ["白血病"], ["leukemia"]),
    _entry("急性髓系白血病", ["急性髓系白血病", "aml"], ["acute myeloid leukemia", "AML"]),
    _entry("急性淋巴细胞白血病", ["急性淋巴细胞白血病", "all"], ["acute lymphoblastic leukemia", "ALL"]),
    _entry("慢性髓系白血病", ["慢性髓系白血病", "cml"], ["chronic myeloid leukemia", "CML"]),
    _entry("慢性淋巴细胞白血病", ["慢性淋巴细胞白血病", "cll"], ["chronic lymphocytic leukemia", "CLL"]),
    _entry("淋巴瘤", ["淋巴瘤"], ["lymphoma"]),
    _entry("弥漫大b细胞淋巴瘤", ["弥漫大b细胞淋巴瘤", "dlbcl"], ["diffuse large B cell lymphoma", "DLBCL"]),
    _entry("霍奇金淋巴瘤", ["霍奇金淋巴瘤"], ["Hodgkin lymphoma"]),
    _entry("滤泡性淋巴瘤", ["滤泡性淋巴瘤"], ["follicular lymphoma"]),
    _entry("多发性骨髓瘤", ["多发性骨髓瘤", "mm"], ["multiple myeloma", "MM"]),
]
