"""Shared UI foundations for BioMedPilot desktop surfaces."""

from app.shared.ui.theme import (
    BioMedPilotButtonRoles,
    BioMedPilotColors,
    BioMedPilotControlHeights,
    BioMedPilotRadii,
    BioMedPilotSpacing,
    BioMedPilotStatusColors,
    BioMedPilotStatusStyle,
    BioMedPilotTypography,
    as_legacy_color_dict,
    as_legacy_control_height_dict,
    as_legacy_font_size_dict,
    as_legacy_radius_dict,
    as_legacy_spacing_dict,
    card_title_qss,
    error_text_qss,
    helper_text_qss,
    page_title_qss,
    shell_sidebar_qss,
    status_style,
    status_styles,
    surface_card_qss,
    warning_text_qss,
)

__all__ = [
    "BioMedPilotButtonRoles",
    "BioMedPilotColors",
    "BioMedPilotControlHeights",
    "BioMedPilotRadii",
    "BioMedPilotSpacing",
    "BioMedPilotStatusColors",
    "BioMedPilotStatusStyle",
    "BioMedPilotTypography",
    "as_legacy_color_dict",
    "as_legacy_control_height_dict",
    "as_legacy_font_size_dict",
    "as_legacy_radius_dict",
    "as_legacy_spacing_dict",
    "card_title_qss",
    "error_text_qss",
    "helper_text_qss",
    "page_title_qss",
    "shell_sidebar_qss",
    "status_style",
    "status_styles",
    "surface_card_qss",
    "warning_text_qss",
]
