from app.shared.local_engines.engine_config import LocalEngineConfig, LocalEngineConfigStore, local_engine_config_from_dict
from app.shared.local_engines.engine_status import (
    ENGINE_STATUS_AVAILABLE,
    ENGINE_STATUS_CONFIGURED_UNVERIFIED,
    ENGINE_STATUS_FAILED,
    ENGINE_STATUS_NOT_CONFIGURED,
    ENGINE_STATUS_UNSUPPORTED_VERSION,
    EngineStatus,
    engine_status_from_dict,
)
from app.shared.local_engines.imagej_fiji_bridge import ImageJFijiBridge
from app.shared.local_engines.imagej_fiji_detector import (
    DEFAULT_IMAGEJ_FIJI_TIMEOUT_SECONDS,
    IMAGEJ_FIJI_ENGINE_ID,
    default_imagej_fiji_status,
    detect_common_imagej_fiji_paths,
    detect_imagej_fiji_status,
    detect_imagej_fiji_runtime_status,
    parse_imagej_fiji_version_output,
    resolve_imagej_fiji_executable,
    run_imagej_fiji_smoke_test,
)
from app.shared.local_engines.imagej_fiji_installer import (
    ImageJFijiRuntimeInstallResult,
    extract_zip_safely,
    locate_imagej_fiji_runtime_executable,
    prepare_imagej_fiji_runtime,
    run_imagej_fiji_macro,
    sha256_file,
)
from app.shared.local_engines.imagej_fiji_runner_contract import build_imagej_fiji_macro_command
from app.shared.local_engines.imagej_fiji_runtime import (
    IMAGEJ_FIJI_DOWNLOAD_BASE_URL,
    IMAGEJ_FIJI_ENGINE_NAME,
    IMAGEJ_FIJI_ENGINE_TYPE,
    IMAGEJ_FIJI_RECOMMENDED_VERSION,
    IMAGEJ_FIJI_RUNTIME_MANIFEST_SCHEMA_VERSION,
    ImageJFijiDownloadAsset,
    ImageJFijiRuntimeManifest,
    default_imagej_fiji_runtime_root,
    imagej_fiji_runtime_manifest_from_dict,
    imagej_fiji_runtime_manifest_path,
    load_imagej_fiji_runtime_manifest,
    select_imagej_fiji_download_asset,
    write_imagej_fiji_runtime_manifest,
)
from app.shared.local_engines.install_guides import imagej_fiji_install_guide_text, imagej_fiji_setup_prompt_text, paddleocr_install_guide_text
from app.shared.local_engines.paddleocr_bridge import PaddleOCRBridge
from app.shared.local_engines.paddleocr_detector import (
    PADDLEOCR_ENGINE_NAME,
    PADDLEOCR_ENGINE_TYPE,
    PADDLEOCR_RECOMMENDED_VERSION,
    default_paddleocr_status,
    detect_paddleocr_runtime_status,
)
from app.shared.local_engines.paddleocr_runtime import (
    PADDLEOCR_ENGINE_ID,
    PADDLEOCR_RUNTIME_MANIFEST_SCHEMA_VERSION,
    PaddleOCRModelAsset,
    PaddleOCRRuntimeManifest,
    default_paddleocr_runtime_root,
    load_paddleocr_runtime_manifest,
    paddleocr_runtime_manifest_from_dict,
    paddleocr_runtime_manifest_path,
)
from app.shared.local_engines.paddleocr_worker_contract import (
    PADDLEOCR_WORKER_MODE_IMAGE,
    PADDLEOCR_WORKER_MODE_PDF,
    PADDLEOCR_WORKER_MODES,
    PADDLEOCR_WORKER_MODULE,
    build_paddleocr_worker_command,
)

__all__ = [
    "ENGINE_STATUS_AVAILABLE",
    "ENGINE_STATUS_CONFIGURED_UNVERIFIED",
    "ENGINE_STATUS_FAILED",
    "ENGINE_STATUS_NOT_CONFIGURED",
    "ENGINE_STATUS_UNSUPPORTED_VERSION",
    "DEFAULT_IMAGEJ_FIJI_TIMEOUT_SECONDS",
    "IMAGEJ_FIJI_DOWNLOAD_BASE_URL",
    "IMAGEJ_FIJI_ENGINE_ID",
    "IMAGEJ_FIJI_ENGINE_NAME",
    "IMAGEJ_FIJI_ENGINE_TYPE",
    "IMAGEJ_FIJI_RECOMMENDED_VERSION",
    "IMAGEJ_FIJI_RUNTIME_MANIFEST_SCHEMA_VERSION",
    "PADDLEOCR_ENGINE_ID",
    "PADDLEOCR_ENGINE_NAME",
    "PADDLEOCR_ENGINE_TYPE",
    "PADDLEOCR_RECOMMENDED_VERSION",
    "PADDLEOCR_RUNTIME_MANIFEST_SCHEMA_VERSION",
    "PADDLEOCR_WORKER_MODE_IMAGE",
    "PADDLEOCR_WORKER_MODE_PDF",
    "PADDLEOCR_WORKER_MODES",
    "PADDLEOCR_WORKER_MODULE",
    "EngineStatus",
    "ImageJFijiBridge",
    "ImageJFijiDownloadAsset",
    "ImageJFijiRuntimeInstallResult",
    "ImageJFijiRuntimeManifest",
    "LocalEngineConfig",
    "LocalEngineConfigStore",
    "PaddleOCRBridge",
    "PaddleOCRModelAsset",
    "PaddleOCRRuntimeManifest",
    "build_imagej_fiji_macro_command",
    "build_paddleocr_worker_command",
    "default_imagej_fiji_status",
    "default_imagej_fiji_runtime_root",
    "default_paddleocr_runtime_root",
    "default_paddleocr_status",
    "detect_common_imagej_fiji_paths",
    "detect_imagej_fiji_status",
    "detect_imagej_fiji_runtime_status",
    "detect_paddleocr_runtime_status",
    "engine_status_from_dict",
    "extract_zip_safely",
    "imagej_fiji_install_guide_text",
    "imagej_fiji_runtime_manifest_from_dict",
    "imagej_fiji_runtime_manifest_path",
    "imagej_fiji_setup_prompt_text",
    "load_imagej_fiji_runtime_manifest",
    "load_paddleocr_runtime_manifest",
    "local_engine_config_from_dict",
    "locate_imagej_fiji_runtime_executable",
    "paddleocr_install_guide_text",
    "paddleocr_runtime_manifest_from_dict",
    "paddleocr_runtime_manifest_path",
    "parse_imagej_fiji_version_output",
    "prepare_imagej_fiji_runtime",
    "resolve_imagej_fiji_executable",
    "run_imagej_fiji_macro",
    "run_imagej_fiji_smoke_test",
    "select_imagej_fiji_download_asset",
    "sha256_file",
    "write_imagej_fiji_runtime_manifest",
]
